LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := WalletApp

LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES := prebuilt/app-release.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

LOCAL_PRODUCT_MODULE := true

include $(BUILD_PREBUILT)